update

diff --git a/assets/wrapper b/assets/wrapper
--- a/assets/wrapper
+++ b/assets/wrapper
@@ -91,9 +91,9 @@ gitlab-ctl reconfigure
 
 # Make sure PostgreSQL is at the latest version.
 # If it fails, print a message with a workaround and exit
-if [ "${GITLAB_SKIP_PG_UPGRADE}" != true ]; then
-    gitlab-ctl pg-upgrade -w || failed_pg_upgrade
-fi
+#if [ "${GITLAB_SKIP_PG_UPGRADE}" != true ]; then
+#    gitlab-ctl pg-upgrade -w || failed_pg_upgrade
+#fi
 
 if [ -n "${GITLAB_POST_RECONFIGURE_SCRIPT+x}" ]; then
   echo "Runnning Post Reconfigure Script..."
